//banner
export const FETCHING_BANNER = 'FETCHING_BANNER';
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_FAILURE = 'FETCH_BANNER_FAILURE';
//channel
export const FETCHING_CHANNEL = 'FETCHING_CHANNEL';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';
// sports
export const FETCHING_SPORTS = 'FETCHING_SPORTS';
export const FETCHING_SPORTS_SUCCESS = 'FETCHING_SPORTS_SUCCESS';
export const FETCHING_SPORTS_FAILURE = 'FETCHING_SPORTS_FAILURE';
