//banner
export const FETCHING_BANNER = 'FETCHING_BANNER';
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_FAILURE = 'FETCH_BANNER_FAILURE';
//channel
export const FETCHING_CHANNEL = 'FETCHING_CHANNEL';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';
//live
export const FETCHING_LIVE = 'FETCHING_LIVE';
export const FETCH_LIVE_SUCCESS = 'FETCH_LIVE_SUCCESS';
export const FETCH_LIVE_FAILURE = 'FETCH_LIVE_FAILURE';
// category
export const FETCHING_CATEGORY = 'FETCHING_CATEGORY';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';
//VOD
export const FETCHING_VOD = 'FETCHING_VOD';
export const FETCH_VOD_SUCCESS = 'FETCH_VOD_SUCCESS';
export const FETCH_VOD_FAILURE = 'FETCH_VOD_FAILURE';
// ADS
export const FETCHING_ADS = 'FETCHING_ADS';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
// NEWS
export const FETCHING_NEWS = 'FETCHING_NEWS';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

//SHOW VIDEO MODAL
export const SHOW_VIDEO_MODAL = 'SHOW_VIDEO_MODAL';

//EPG FROM CHANNEL
export const FETCHING_EPGS = 'FETCHING_EPGS';
export const FETCH_EPGS_SUCCESS = 'FETCH_EPGS_SUCCESS';
export const FETCH_EPGS_FAILURE = 'FETCH_EPGS_FAILURE';

// EPG WITH GENRES
export const FETCHING_EPG_GENRES = 'FETCHING_EPG_GENRES';
export const FETCH_EPG_GENRES_SUCCESS = 'FETCH_EPG_GENRES_SUCCESS';
export const FETCH_EPG_GENRES_FAILURE = 'FETCH_EPG_GENRES_FAILURE';

// EPG WITH SERIESID
export const FETCHING_EPG_SERIES = 'FETCHING_EPG_SERIES';
export const FETCH_EPG_SERIES_SUCCESS = 'FETCH_EPG_SERIES_SUCCESS';
export const FETCH_EPG_SERIES_FAILURE = 'FETCH_EPG_SERIES_FAILURE';

// SHOW CHANNEL MODAL
export const SHOW_CHANNEL_MODAL = 'SHOW_CHANNEL_MODAL';

// GET GENRES CONTENT
export const FETCHING_GENRES_CONTENT = 'FETCHING_GENRES_CONTENT';
export const FETCH_GENRES_CONTENT_SUCCESS = 'FETCH_GENRES_CONTENT_SUCCESS';
export const FETCH_GENRES_CONTENT_FAILTURE = 'FETCH_GENRES_CONTENT_FAILURE';

// FETCHING BOOK LIST FROM STB
export const FETCHING_BOOK_LIST = 'FETCHING_BOOK_LIST'
export const FETCH_BOOK_LIST_SUCCESS = 'FETCH_BOOK_LIST_SUCCESS'
export const FETCH_BOOK_LIST_FAILURE = 'FETCH_BOOK_LIST_FAILURE'
