//banner
export const FETCHING_BANNER = 'FETCHING_BANNER';
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_FAILURE = 'FETCH_BANNER_FAILURE';
//channel
export const FETCHING_CHANNEL = 'FETCHING_CHANNEL';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';
//live
export const FETCHING_LIVE = 'FETCHING_LIVE';
export const FETCH_LIVE_SUCCESS = 'FETCH_LIVE_SUCCESS';
export const FETCH_LIVE_FAILURE = 'FETCH_LIVE_FAILURE';
//VOD
export const FETCHING_VOD = 'FETCHING_VOD';
export const FETCH_VOD_SUCCESS = 'FETCH_VOD_SUCCESS';
export const FETCH_VOD_FAILURE = 'FETCH_VOD_FAILURE';