# Uncomment the next line to define a global platform for your project
source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'OnAppTV' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OnAppTV
  pod 'Brightcove-Player-Core/dynamic'
  #pod 'Brightcove-Player-SDK-SidecarSubtitles/dynamic'

  target 'OnAppTVTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'OnAppTV-tvOS' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#
#  # Pods for OnAppTV-tvOS
#
#  target 'OnAppTV-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end

